[package]
name    = "iata"
version = "0.1.1"
authors = [
    "Anton Dutov <anton.dutov@gmail.com>",
    "Mike Lubinets <lubinetsm@yandex.ru>",
]

license     = "MIT"
description = "Some implementations of IATA resolutions"
repository  = "https://github.com/anton-dutov/iata-rs"

[dependencies]
nom    = "3.2"
chrono = "0.4"
