[package]
name        = "iata"
version     = "0.1.0"
authors     = ["Anton Dutov <anton.dutov@gmail.com>"]
license     = "MIT"
description = "Some implementations of IATA resolutions"
repository  = "https://github.com/anton-dutov/iata-rs"

[dependencies]
nom    = "3.2"
chrono = "0.4"
